services:
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-fraud:latest
    hostname: api1
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  api2:
    <<: *api
    build: !reset null
    hostname: api2
    environment:
      - SOCK=/run/sock/api2.sock

  haproxy:
    image: haproxy:2.9-alpine
    restart: always
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sock:
